/*
 * LinkedApplet.java
 *
 */

/**
 *
 * @author  dls102
 */
public class LinkedApplet_Niedzielski extends javax.swing.JApplet {
    
    int nameC=0, yearC=0, titleC=0;
    /** Initializes the applet NewJApplet */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
            setSize(480, 460);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    public void displayText(String s)
    {
        display.setText(s);
    }
    
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();
        buildDisplayButton = new javax.swing.JButton();
        fileNameLabel = new javax.swing.JLabel();
        filenameField = new javax.swing.JTextField();
        addItemButton = new javax.swing.JButton();
        removeItemButton = new javax.swing.JButton();
        SortByNameButton = new javax.swing.JButton();
        sortByYearsButton = new javax.swing.JButton();
        sortByTitleSalaryButton = new javax.swing.JButton();

        display.setColumns(20);
        display.setRows(5);
        jScrollPane1.setViewportView(display);

        buildDisplayButton.setText("Build and Display");
        buildDisplayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildDisplayButtonActionPerformed(evt);
            }
        });

        fileNameLabel.setText("Enter Filename: ");

        filenameField.setText("sampledata.txt");

        addItemButton.setText("Add Item");
        addItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemButtonActionPerformed(evt);
            }
        });

        removeItemButton.setText("Remove Item");
        removeItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeItemButtonActionPerformed(evt);
            }
        });

        SortByNameButton.setText("Sort By Name");
        SortByNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortByNameButtonActionPerformed(evt);
            }
        });

        sortByYearsButton.setText("Sort By Years");
        sortByYearsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortByYearsButtonActionPerformed(evt);
            }
        });

        sortByTitleSalaryButton.setText("Sort By Title and Salary");
        sortByTitleSalaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortByTitleSalaryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buildDisplayButton)
                                .addGap(18, 18, 18)
                                .addComponent(addItemButton)
                                .addGap(18, 18, 18)
                                .addComponent(removeItemButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fileNameLabel)
                                .addGap(20, 20, 20)
                                .addComponent(filenameField))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(SortByNameButton)
                                .addGap(18, 18, 18)
                                .addComponent(sortByYearsButton)
                                .addGap(18, 18, 18)
                                .addComponent(sortByTitleSalaryButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileNameLabel)
                    .addComponent(filenameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buildDisplayButton)
                    .addComponent(addItemButton)
                    .addComponent(removeItemButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SortByNameButton)
                    .addComponent(sortByYearsButton)
                    .addComponent(sortByTitleSalaryButton))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buildDisplayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildDisplayButtonActionPerformed
        if (manager.initialize(filenameField.getText()))  // true = operation successful
            display.setText(manager.print());
    }//GEN-LAST:event_buildDisplayButtonActionPerformed

    private void sortByYearsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByYearsButtonActionPerformed
        // TODO add your handling code here:
        manager.sortYears();
        titleC=0;//counters for sort rerun
        nameC=0;
        yearC=1;
        display.setText(manager.print());
    }//GEN-LAST:event_sortByYearsButtonActionPerformed

    private void SortByNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortByNameButtonActionPerformed
        // TODO add your handling code here:
        manager.sortName();
        titleC=0;//counters for sort rerun
        nameC=1;
        yearC=0;
        display.setText(manager.print());
    }//GEN-LAST:event_SortByNameButtonActionPerformed

    private void sortByTitleSalaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByTitleSalaryButtonActionPerformed
        // TODO add your handling code here:
        manager.sortTitleSalary();
        manager.sortTitleSalary();//run 2x to sort by title then salary
        titleC=1;//counters for sort rerun
        nameC=0;
        yearC=0;        
        display.setText(manager.print());
        
    }//GEN-LAST:event_sortByTitleSalaryButtonActionPerformed

    private void removeItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeItemButtonActionPerformed
        // TODO add your handling code here:
        manager.removeItem();
        display.setText(manager.print());//reprint
    }//GEN-LAST:event_removeItemButtonActionPerformed

    private void addItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemButtonActionPerformed
        // TODO add your handling code here:
        manager.addItem();
        if(titleC==1)
            manager.sortTitleSalary();
        else if(nameC==1)
            manager.sortName();
        else
            manager.sortYears();
        display.setText(manager.print());//rerun last sort method and reprint
    }//GEN-LAST:event_addItemButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SortByNameButton;
    private javax.swing.JButton addItemButton;
    private javax.swing.JButton buildDisplayButton;
    private javax.swing.JTextArea display;
    private javax.swing.JLabel fileNameLabel;
    private javax.swing.JTextField filenameField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeItemButton;
    private javax.swing.JButton sortByTitleSalaryButton;
    private javax.swing.JButton sortByYearsButton;
    // End of variables declaration//GEN-END:variables
    
    private LinkManager manager = new LinkManager(this);

    private Object LinkManager() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
